#!/bin/bash

echo "Auth0 Configuration Instructions"
echo "================================"
echo ""
echo "Please update your Auth0 application with the following settings:"
echo ""
echo "1. Go to: https://manage.auth0.com/dashboard/eu/dev-y1vqybc2gwjuo8dp/applications/SDfC8Bj7hNWjusrFhHDgPumhDyoJVr4C/settings"
echo ""
echo "2. Update the following fields:"
echo ""
echo "Allowed Callback URLs (add all):"
echo "- https://airesearchprojects.com/callback"
echo "- https://gemini-fullstack-langgraph-quickstart-75j40mn6r.vercel.app/callback"  
echo "- https://gemini-fullstack-langgraph-quickstart.vercel.app/callback"
echo "- http://localhost:5173/callback"
echo "- http://localhost:3000/callback"
echo ""
echo "Allowed Logout URLs (add all):"
echo "- https://airesearchprojects.com/login"
echo "- https://gemini-fullstack-langgraph-quickstart-75j40mn6r.vercel.app/login"
echo "- https://gemini-fullstack-langgraph-quickstart.vercel.app/login"
echo "- http://localhost:5173/login"
echo "- http://localhost:3000/login"
echo ""
echo "Allowed Web Origins (add all):"
echo "- https://airesearchprojects.com"
echo "- https://gemini-fullstack-langgraph-quickstart-75j40mn6r.vercel.app"
echo "- https://gemini-fullstack-langgraph-quickstart.vercel.app"
echo "- http://localhost:5173"
echo "- http://localhost:3000"
echo ""
echo "3. Enable Social Connections:"
echo "- Google (google-oauth2)"
echo "- Facebook"
echo "- Create custom connections for VK and Yandex"
echo ""
echo "4. Save all changes"
echo ""
echo "Latest deployment URL: https://gemini-fullstack-langgraph-quickstart-75j40mn6r.vercel.app"